ARG NPM_REGISTRY=https://registry.npm.taobao.org
FROM node:12-slim AS gui-builder
COPY gui/package.json gui/package-lock.json /work/gui/
RUN cd /work/gui && npm config set registry ${NPM_REGISTRY} && npm ci && npm cache clean --force
COPY gui /work/gui
RUN cd /work/gui && npm run build && npm cache clean --force


FROM node:12-slim AS production
COPY sources.list /etc/apt/sources.list
RUN apt-get update && \
	apt-get install -y --no-install-recommends ffmpeg && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /work/
COPY package.json package-lock.json .
RUN npm config set registry ${NPM_REGISTRY} && npm ci && npm cache clean --force

COPY anyproxy/ ./anyproxy/
COPY --from=gui-builder /work/gui/dist /work/gui/dist

COPY utils.js api-server.js server.js database.js docker-entrypoint.sh .
ENTRYPOINT ["/work/docker-entrypoint.sh"]
